"""empty message

Revision ID: d578676f0d70
Revises: 
Create Date: 2022-06-27 17:59:16.588746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd578676f0d70'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Descuento',
    sa.Column('id_descuento', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('fecha', sa.String(length=20), nullable=False),
    sa.Column('porcentaje', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_descuento')
    )
    op.create_table('Despacho',
    sa.Column('id_despacho', sa.Integer(), nullable=False),
    sa.Column('direccion', sa.String(length=250), nullable=False),
    sa.Column('fecha_entrega', sa.String(length=20), nullable=True),
    sa.Column('rut_recibe', sa.String(length=250), nullable=True),
    sa.Column('nombre_recibe', sa.String(length=250), nullable=True),
    sa.Column('esto_despacho', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('comuna_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comuna_id'], ['Comuna.id_comuna'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['Venta.id_venta'], ),
    sa.PrimaryKeyConstraint('id_despacho')
    )
    op.create_table('Producto',
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=250), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('categoria', sa.String(length=250), nullable=False),
    sa.Column('valor_venta', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=False),
    sa.Column('imagen', sa.String(length=250), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_producto')
    )
    op.create_table('Region',
    sa.Column('id_region', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_region')
    )
    op.create_table('Venta',
    sa.Column('id_venta', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.String(length=20), nullable=False),
    sa.Column('descuento', sa.Integer(), nullable=True),
    sa.Column('sub_total', sa.Integer(), nullable=False),
    sa.Column('iva', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('despacho_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['Usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['despacho_id'], ['Despacho.id_despacho'], ),
    sa.PrimaryKeyConstraint('id_venta')
    )
    op.create_table('Comuna',
    sa.Column('id_comuna', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['Region.id_region'], ),
    sa.PrimaryKeyConstraint('id_comuna')
    )
    op.create_table('Descuento_Producto',
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('descuento_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.String(length=20), nullable=True),
    sa.Column('fecha_termino', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['descuento_id'], ['Descuento.id_descuento'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['Producto.id_producto'], ),
    sa.PrimaryKeyConstraint('producto_id', 'descuento_id')
    )
    op.create_table('Detalle',
    sa.Column('id_detalle', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.Column('descuento', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['Producto.id_producto'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['Venta.id_venta'], ),
    sa.PrimaryKeyConstraint('id_detalle')
    )
    op.create_table('Usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('rut', sa.Integer(), nullable=False),
    sa.Column('dv', sa.Integer(), nullable=True),
    sa.Column('primer_nombre', sa.String(length=250), nullable=False),
    sa.Column('segundo_nombre', sa.String(length=250), nullable=True),
    sa.Column('apellido_paterno', sa.String(length=250), nullable=False),
    sa.Column('apellido_materno', sa.String(length=250), nullable=True),
    sa.Column('direccion', sa.String(length=250), nullable=False),
    sa.Column('fono', sa.Integer(), nullable=False),
    sa.Column('correo', sa.String(length=250), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('comuna_id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=True),
    sa.Column('suscrito', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['comuna_id'], ['Comuna.id_comuna'], ),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_table('Donacion',
    sa.Column('id_donacion', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.String(length=20), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['Usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_donacion')
    )
    op.create_table('Suscripcion',
    sa.Column('id_suscripcion', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.String(length=20), nullable=False),
    sa.Column('fecha_termino', sa.String(length=20), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['Usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_suscripcion')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Suscripcion')
    op.drop_table('Donacion')
    op.drop_table('Usuario')
    op.drop_table('Detalle')
    op.drop_table('Descuento_Producto')
    op.drop_table('Comuna')
    op.drop_table('Venta')
    op.drop_table('Region')
    op.drop_table('Producto')
    op.drop_table('Despacho')
    op.drop_table('Descuento')
    # ### end Alembic commands ###
